name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Test
      uses: python:3.7.2
      run: |
        pip install -r requirements.txt
        python manage.py test
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        FLASK_END: 'test'
