name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.3'
    - name: Test
      run: |
        pip install -r requirements.txt
        python manage.py test
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        FLASK_END: 'test'
